[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.qwq.work"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
